In [1]:
from sklearn import datasets, metrics
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from sklearn.neural_network import MLPClassifier
iris = datasets.load_iris()

print(iris.feature_names)
print(iris.target_names)
print(iris.data.shape)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
(150, 4)


In [2]:
X,y = datasets.load_iris(return_X_y = True) 

X_train = X[range(1,150,2),:]
y_train = y[range(1,150,2)]

#print(y_train.shape)
#print(X_train.shape)

X_test = X[range(0,150,2),:]
y_test = y[range(0,150,2)]

#print(X_train)
#print(y_train)

clf = MLPClassifier(solver = 'sgd', hidden_layer_sizes=50, max_iter= 200)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(y_pred)

print(metrics.confusion_matrix(y_test, y_pred))
# Printing the precision and recall, among other metrics
print(metrics.classification_report(y_test, y_pred))



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2
 1 1 2 1 1 2 1 1 2 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
[[25  0  0]
 [ 0 18  7]
 [ 0  0 25]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.72      0.84        25
           2       0.78      1.00      0.88        25

    accuracy                           0.91        75
   macro avg       0.93      0.91      0.90        75
weighted avg       0.93      0.91      0.90        75



/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


#10.2 K-Means Clustering

In [ ]:
from sklearn.cluster import KMeans

clf = KMeans(sj)