## MLP Classifier for Iris dataset

In [29]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn import datasets, metrics

In [30]:
X,y = datasets.load_iris(return_X_y=True)

In [31]:
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

In [32]:
print(X_train.shape,y_train.shape)

(75, 4) (75,)


In [33]:
X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

In [34]:
print(X_test.shape,y_test.shape)

(75, 4) (75,)


In [35]:
clf = MLPClassifier(solver = 'adam', hidden_layer_sizes=(80), max_iter=500)

In [36]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=80, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [37]:
prediction = clf.predict(X_test)
print(prediction)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 2 2 2 2 2 2 2
 2]


In [38]:
print(clf.predict_proba(X_test))

[[9.89620216e-01 1.03797835e-02 5.19300857e-10]
 [9.89466845e-01 1.05331541e-02 1.18847605e-09]
 [9.96377248e-01 3.62275187e-03 6.21901853e-11]
 [9.94957758e-01 5.04224178e-03 1.26513593e-10]
 [9.91077764e-01 8.92223534e-03 3.18440190e-10]
 [9.93398358e-01 6.60164190e-03 3.57403916e-10]
 [9.96244523e-01 3.75547640e-03 2.00056206e-10]
 [9.99397179e-01 6.02821081e-04 1.10064808e-12]
 [9.96435513e-01 3.56448716e-03 6.79335815e-11]
 [9.97788544e-01 2.21145590e-03 3.22739957e-11]
 [9.96599809e-01 3.40019078e-03 9.40451614e-11]
 [9.80822563e-01 1.91774341e-02 3.24445620e-09]
 [9.81952061e-01 1.80479374e-02 1.30652235e-09]
 [9.96048639e-01 3.95136051e-03 5.13984637e-11]
 [9.89150347e-01 1.08496516e-02 1.08399118e-09]
 [9.92695096e-01 7.30490380e-03 1.76939738e-10]
 [9.99438953e-01 5.61047396e-04 7.46562071e-13]
 [9.96376858e-01 3.62314240e-03 5.43723877e-11]
 [9.98035753e-01 1.96424722e-03 2.04986954e-11]
 [9.94938781e-01 5.06121858e-03 1.00522387e-10]
 [9.48100483e-01 5.18994879e-02 2.889907

In [39]:
print(metrics.accuracy_score(y_test, prediction, normalize=True))

0.96


In [40]:
print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75



In [41]:
print(metrics.confusion_matrix(y_test, prediction))

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


## Using MLPRegressor for Boston dataset

In [42]:
XB, yB = datasets.load_boston(return_X_y = True)

Xb_train = XB[range(0,XB.shape[0],2),:]
yb_train = yB[range(0,XB.shape[0],2)]

Xb_test = XB[range(1,XB.shape[0],2),:]
yb_test = yB[range(1,XB.shape[0],2)]

print(Xb_train.shape, yb_train.shape,'\n', Xb_test.shape, yb_test.shape)

(253, 13) (253,) 
 (253, 13) (253,)


In [43]:
clfr = MLPRegressor(hidden_layer_sizes=(75,40),solver = 'adam', max_iter=1000)
clfr.fit(Xb_train, yb_train)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(75, 40), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=1000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [44]:
predictionsB = clfr.predict(Xb_test)
print(predictionsB)

[29.00484333 31.09014126 30.81549744 17.96109004 16.74258892 20.6356361
 24.06717358 23.79760009 18.14224516 21.3434383  19.8953543  15.81153533
 13.17052458 13.3746916  19.97105813 19.56653919 13.99622985 25.5171819
 24.85489076 32.94430982 27.51872859 25.76741853 23.1446274  22.48525967
 21.44749771 28.42271121 25.31529833 36.99263152 37.72605889 24.45437685
 21.86511768 23.83118158 30.09412929 23.28678975 21.90097913 22.39494235
 25.05140692 20.59195996 19.94787592 21.65906536 27.89124871 25.07415045
 27.88492534 26.96546855 29.36719074 27.55466699 25.30118033 23.85875277
 31.47329323 28.84321362 24.46413854 21.30115656 19.93885149 20.42072969
 19.95628393 24.077031   20.71189299 18.52708352 23.72213165 19.54885653
 21.66767009 15.81711374 22.39270834 19.58548105 18.32499174 24.03141077
 21.03641057 20.40265277 22.5122754  19.19995339  5.9795445  12.85334274
  6.57810494  9.77155418 15.27531933 22.77967009 15.80848734 10.93813857
 30.51496158 28.51127679 32.00927791 32.66659993 18.1

In [45]:
print(metrics.r2_score(yb_test, predictionsB))

0.6410352091811733


In [46]:
print(metrics.mean_absolute_error(yb_test, predictionsB))

3.9153959265679994


In [47]:
print(metrics.mean_squared_error(yb_test, predictionsB))

29.71104426846873


## K-mean Clustering on Iris dataset

In [48]:
import numpy
import pandas as pd
from sklearn import datasets,metrics
from sklearn.cluster import KMeans

In [49]:
data,target = datasets.load_iris(return_X_y=True)

In [50]:
X_train = data[range(0,150,2),:]
X_test = data[range(1,150,2),:]
print(X_train.shape)
print(X_test.shape)

(75, 4)
(75, 4)


In [51]:
model = KMeans(n_clusters=3)
model.fit(X_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [52]:
print(model.labels_)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 0 2 2
 2]


In [53]:
prediction = model.predict(X_test)
prediction

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 0], dtype=int32)

In [55]:
print(model.cluster_centers_)

[[5.88148148 2.74444444 4.34444444 1.41111111]
 [5.024      3.48       1.456      0.228     ]
 [6.67826087 2.98695652 5.63043478 2.06956522]]
