#Practical 9-  Perceptron Learning
18BCE246

#3-bit AND-input

In [2]:
import pandas as pd
import numpy as np

input = np.array([[0,	0,	0,	0],
[0,	0,	1,	0],
[0,	1,	0,	0],
[0,	1,	1,	0],
[1,	0,	0,	0],
[1,	0,	1,	0],
[1,	1,	0,	0],
[1,	1,	1,	1]])

In [4]:
b = -0.1 #np.random.randn()
w = np.random.randn(input.shape[1]-1)
print(w)
epochs = 10
lr = .1

n_datapts = input.shape[0]
n_features = input.shape[1]-1

for i in range(0,epochs):
  for j in range(0,n_datapts):
    net_ip = w.dot(input[j,0:n_features].T) + b
    
    a = net_ip>=0
    err = input[j,3] - a
    w = w+ (lr*err)*(input[j,0:n_features])
    b += lr*err

#prediction
predict = input[:,0:3]
predicted = []
for j in range(0,predict.shape[0]):
    predicted.append( ((w.dot(predict[j].T)+b) >=0))
print(predicted)
print(w)
print(b)


[ 0.17928571  1.17959157 -0.59372864]
[False, False, False, True, False, False, True, True]
[0.27928571 0.57959157 0.20627136]
-0.7


In [5]:
from sklearn import metrics
print(metrics.accuracy_score(input[:,3],predicted,normalize = True))

0.75


Features with real no. values

In [6]:
input_2 = np.array([[0, 	0],
[0.17,	 0],
[0.33, 0],
[0.5, 0],
[0.67, 	1],
[0.83,	1],
[1,	1]])

In [12]:
#w = np.zeros(input.shape[1]-1)
b = -0.2
w = np.array([-0.36])
print(w)
epochs = 8
lr = .1

n_datapts = input_2.shape[0]
n_features = input_2.shape[1]-1

for i in range(0,epochs):
  for j in range(0,n_datapts):
    net_ip = w.dot(input_2[j,0:n_features].T) +b
    print("Net ip: ",net_ip)
    
    a = net_ip>=0
    err = input_2[j,1] - a
    print("update to add : ",(lr*err)*(input[j,0:n_features]))
    w = w+ (lr*err)*(input_2[j,0:n_features])
    b += lr*err
    print("weights end1",w)
    print("bias",b)
    print("-----------------------------")

#prediction
predict = input_2[:,0]
predicted = []
for j in range(0,predict.shape[0]):
    predicted.append( ((w.dot(predict[j].T)+b) >=0))
print(predicted)
print("FinalWeigh, w = ",w)
print("FinalBias, b = ",b)

[-0.36]
Net ip:  -0.2
update to add :  [0.]
weights end1 [-0.36]
bias -0.2
-----------------------------
Net ip:  -0.2612
update to add :  [0.]
weights end1 [-0.36]
bias -0.2
-----------------------------
Net ip:  -0.31880000000000003
update to add :  [0.]
weights end1 [-0.36]
bias -0.2
-----------------------------
Net ip:  -0.38
update to add :  [0.]
weights end1 [-0.36]
bias -0.2
-----------------------------
Net ip:  -0.44120000000000004
update to add :  [0.1]
weights end1 [-0.293]
bias -0.1
-----------------------------
Net ip:  -0.34319
update to add :  [0.1]
weights end1 [-0.21]
bias 0.0
-----------------------------
Net ip:  -0.20999999999999996
update to add :  [0.1]
weights end1 [-0.11]
bias 0.1
-----------------------------
Net ip:  0.1
update to add :  [-0.]
weights end1 [-0.11]
bias 0.0
-----------------------------
Net ip:  -0.018699999999999994
update to add :  [0.]
weights end1 [-0.11]
bias 0.0
-----------------------------
Net ip:  -0.036299999999999985
update to add :

In [13]:
print(metrics.accuracy_score(input_2[:,1],predicted,normalize = True))

0.8571428571428571


#Binary Classification for multiple non 0-1 valued features

In [14]:
input_3 = np.array([[0, 1.2,	0],
[0.17,	3.6, 0],
[0.33, 1.2,0],
[0.5, 2.13,	0],
[0.67, 3.57,	1],
[0.83, 1.12,	1],
[1, .03,	1]])

In [27]:
#w = np.zeros(input.shape[1]-1)
b = -0.1
w = np.array([-0.36,0.45])
epochs = 4
lr = .1

n_datapts = input_3.shape[0]
n_features = input_3.shape[1]-1

for i in range(0,epochs):
  print("**Initiating Epoch ",i)
  for j in range(0,n_datapts):
    net_ip = w.dot(input_2[j,0:n_features].T) +b
    a = net_ip>=0
    err = input_3[j,2] - a
    w = w+ (lr*err)*(input_3[j,0:n_features])
    b += lr*err

#prediction
predict = input_3[:,0:n_features]
predicted = []
for j in range(0,predict.shape[0]):
    #print(f"Predict pair{j} : ",predict[j].T)
    predicted.append ((w.dot(predict[j].T)+b) >=0)

for i in predicted:
  print('  ',i)
print("FinalWeight, w = ",w)
print("FinalBias, b = ",b)

**Initiating Epoch  0
**Initiating Epoch  1
**Initiating Epoch  2
**Initiating Epoch  3
   True
   True
   True
   True
   True
   True
   False
FinalWeight, w =  [-0.077  0.208]
FinalBias, b =  -0.1


In [28]:
print(metrics.accuracy_score(input_3[:,2],predicted,normalize = True))


0.2857142857142857


#On PIMA_Indian_Diabetes DATASET

About dataset

In [29]:
data = pd.read_csv(filepath_or_buffer='/content/drive/My Drive/Colab Notebooks/ML_submissions/prac8_AND-GatePerceptronNN/diabetes.csv',header='infer')
data = pd.DataFrame(data)
print("Columns are: ",data.columns)

Columns are:  Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [41]:
w = np.random.randn(1,data.shape[1]-1)
b = -0.1

epochs = 8
lr = .5

n_datapts = data.shape[0]
n_features = data.shape[1]-1

for i in range(0,epochs):
  for j in range(0,n_datapts):
    net_ip = w.dot(data.iloc[j,0:n_features].T) +b
    a = net_ip>=0
    err = data.iloc[j,data.shape[1]-1] - a
    input_array = np.array(list(data.iloc[j,0:n_features]))
    w = w+ (lr*err)*input_array
    b += lr*err
   
print("Weights are :" ,w)
print("Bias is : ",b)

Weights are : [[ 362.81230475  123.03914098 -218.16122435 -135.4318461    38.74546795
     8.99866599   29.38342743  -73.17011941]]
Bias is :  [-119.1]


In [42]:
#prediction

predicted = list()
for j in range(n_datapts):
    #print(f"Predict pair{j} : ",predict[j].T)
    predicted.append ((w.dot(data.iloc[j,0:n_features])+b) >=0)
print(" ".join(map(str,predicted)))

[False] [False] [ True] [False] [ True] [False] [False] [ True] [ True] [False] [False] [ True] [False] [ True] [ True] [ True] [False] [False] [ True] [False] [False] [False] [ True] [False] [False] [ True] [ True] [False] [ True] [False] [False] [ True] [False] [False] [False] [ True] [ True] [False] [False] [False] [ True] [False] [False] [ True] [ True] [ True] [ True] [False] [False] [ True] [False] [False] [False] [ True] [ True] [False] [ True] [False] [False] [False] [ True] [ True] [False] [ True] [False] [False] [False] [False] [False] [False] [False] [ True] [False] [ True] [False] [False] [False] [False] [ True] [False] [ True] [ True] [False] [False] [False] [False] [False] [False] [ True] [False] [False] [ True] [False] [False] [False] [ True] [False] [False] [False] [False] [ True] [ True] [False] [False] [False] [ True] [False] [ True] [False] [False] [ True] [ True] [False] [False] [ True] [False] [False] [False] [False] [False] [False] [False] [False] [False] [False] 

In [43]:
print(metrics.accuracy_score(data.iloc[:,8],predicted,normalize = True))
print(metrics.confusion_matrix(data.iloc[:,8],predicted))
print(metrics.classification_report(data.iloc[:,8],predicted))

0.6575520833333334
[[358 142]
 [121 147]]
              precision    recall  f1-score   support

           0       0.75      0.72      0.73       500
           1       0.51      0.55      0.53       268

    accuracy                           0.66       768
   macro avg       0.63      0.63      0.63       768
weighted avg       0.66      0.66      0.66       768

